cloud:
  aws:
    credentials:
      accessKey: AKIAVYCNEZ7DTC42HC6B
      secretKey: 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
    # s3, region, stack은 credentials와 같은 레벨이어야 합니다.
    s3:
      bucket: hanjum
      dir: images/
    region:
      static: ap-northeast-2
    stack:
      auto: false

# spring은 cloud와 같은 레벨이어야 합니다.
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB