name: NewsHanjum CI/CD

on:
  push:
    branches: [ "main" ] # Triggers on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Deploy to EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PEM_KEY }}
          script: |
            # 1. Navigate to the project directory
            cd /home/ubuntu/2025_HANJUM_TEAM_32_BE
            
            # 2. Pull the latest changes from the main branch
            git pull
            
            echo "${{ secrets.APPLICATION_PROD_YML }}" > src/main/resources/application-prod.yml
            echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
            echo "${{ secrets.APPLICATION_SWAGGER_YML }}" > src/main/resources/application-swagger.yml
            echo "${{ secrets.APPLICATION_S3_YML }}" > src/main/resources/application-s3.yml
            echo "${{ secrets.APPLICATION_LOCAL_YML }}" > src/main/resources/application-local.yml
            
            # 4. Give gradlew execute permissions on the server
            chmod +x ./gradlew
            
            # 5. Rebuild the application with the new code and configurations
            ./gradlew clean build
            
            # 6. Stop and restart the service using systemd
            sudo systemctl restart newshanjum
            
            # (Optional but recommended) Check the service status
            # The sleep command gives the service a moment to start up
            sleep 5
            sudo systemctl status newshanjum
